"""initial_schema

Revision ID: e01e8cb486aa
Revises: 
Create Date: 2026-10-05 13:19:04.837851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01e8cb486aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tail_number', sa.String(length=32), nullable=False),
    sa.Column('aircraft_type', sa.String(length=64), nullable=False),
    sa.Column('squadron', sa.String(length=128), nullable=False),
    sa.Column('base_location', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('total_flight_hours', sa.Float(), nullable=False),
    sa.Column('flight_cycles', sa.Integer(), nullable=False),
    sa.Column('commissioning_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_scheduled_inspection', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircraft_aircraft_type'), ['aircraft_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_base_location'), ['base_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_squadron'), ['squadron'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_tail_number'), ['tail_number'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    op.create_table('maintenance_bays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bay_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hangar_name', sa.String(length=128), nullable=False),
    sa.Column('bay_type', sa.String(length=64), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_bays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_bays_bay_code'), ['bay_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_maintenance_bays_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_bays_id'), ['id'], unique=False)

    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('metric_precision', sa.Float(), nullable=False),
    sa.Column('metric_recall', sa.Float(), nullable=False),
    sa.Column('metric_f1', sa.Float(), nullable=False),
    sa.Column('metric_roc_auc', sa.Float(), nullable=False),
    sa.Column('metric_rul_rmse', sa.Float(), nullable=False),
    sa.Column('metric_rul_score', sa.Float(), nullable=False),
    sa.Column('false_positive_rate', sa.Float(), nullable=False),
    sa.Column('false_negative_rate', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_evaluations_evaluation_timestamp'), ['evaluation_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_evaluations_model_name'), ['model_name'], unique=False)

    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('compatible_aircraft_types', sa.JSON(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_threshold', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('storage_location', sa.String(length=64), nullable=False),
    sa.Column('reorder_order_placed', sa.Boolean(), nullable=False),
    sa.Column('predicted_demand_30d', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_parts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_parts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spare_parts_part_number'), ['part_number'], unique=True)

    op.create_table('technicians',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.String(length=64), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('shift', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technicians_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_technicians_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_technicians_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technicians_specialty'), ['specialty'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('aircraft_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=False),
    sa.Column('component_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('degradation_percent', sa.Float(), nullable=False),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aircraft_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aircraft_components_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_components_component_code'), ['component_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_components_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aircraft_components_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_aircraft_components_zone'), ['zone'], unique=False)

    op.create_table('document_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_entities', sa.JSON(), nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['component_id'], ['aircraft_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_records_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_records_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_records_id'), ['id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_probability_72h', sa.Float(), nullable=False),
    sa.Column('baseline_probability', sa.Float(), nullable=False),
    sa.Column('rul_hours', sa.Float(), nullable=False),
    sa.Column('rul_lower_bound', sa.Float(), nullable=False),
    sa.Column('rul_upper_bound', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['aircraft_components.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_timestamp'), ['timestamp'], unique=False)

    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vibration', sa.Float(), nullable=False),
    sa.Column('egt', sa.Float(), nullable=False),
    sa.Column('oil_pressure', sa.Float(), nullable=False),
    sa.Column('oil_temperature', sa.Float(), nullable=False),
    sa.Column('fuel_flow', sa.Float(), nullable=False),
    sa.Column('hydraulic_pressure', sa.Float(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=False),
    sa.Column('n1_rpm', sa.Float(), nullable=False),
    sa.Column('n2_rpm', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('sensor_status', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['aircraft_components.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index('ix_telemetry_aircraft_timestamp', ['aircraft_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_is_anomaly'), ['is_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_telemetry_timestamp_brin', ['timestamp'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_rule', sa.String(length=128), nullable=False),
    sa.Column('evidence_summary', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['aircraft_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('prediction_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('importance_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_evidence_prediction_id'), ['prediction_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_number', sa.String(length=64), nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('bay_id', sa.Integer(), nullable=True),
    sa.Column('required_spare_id', sa.Integer(), nullable=True),
    sa.Column('required_spare_quantity', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('baseline_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bay_id'], ['maintenance_bays.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['component_id'], ['aircraft_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['required_spare_id'], ['spare_parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bay_id', 'scheduled_start', name='uq_bay_schedule_slot'),
    sa.UniqueConstraint('technician_id', 'scheduled_start', name='uq_technician_schedule_slot')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index('ix_wo_schedule_window', ['scheduled_start', 'scheduled_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_bay_id'), ['bay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_required_spare_id'), ['required_spare_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_scheduled_end'), ['scheduled_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_technician_id'), ['technician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_work_order_number'), ['work_order_number'], unique=True)

    op.create_table('maintenance_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_id', sa.String(length=32), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome_verified', sa.Boolean(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['aircraft_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_events_aircraft_id'), ['aircraft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_events_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_events_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_events_component_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_events_aircraft_id'))

    op.drop_table('maintenance_events')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_work_order_number'))
        batch_op.drop_index(batch_op.f('ix_work_orders_technician_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_work_orders_scheduled_end'))
        batch_op.drop_index(batch_op.f('ix_work_orders_required_spare_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_priority'))
        batch_op.drop_index(batch_op.f('ix_work_orders_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_component_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_bay_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_approval_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_aircraft_id'))
        batch_op.drop_index('ix_wo_schedule_window')

    op.drop_table('work_orders')
    with op.batch_alter_table('prediction_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_evidence_prediction_id'))

    op.drop_table('prediction_evidence')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_component_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_aircraft_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_timestamp_brin')
        batch_op.drop_index(batch_op.f('ix_telemetry_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_is_anomaly'))
        batch_op.drop_index(batch_op.f('ix_telemetry_component_id'))
        batch_op.drop_index('ix_telemetry_aircraft_timestamp')
        batch_op.drop_index(batch_op.f('ix_telemetry_aircraft_id'))

    op.drop_table('telemetry')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_predictions_risk_level'))
        batch_op.drop_index(batch_op.f('ix_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_component_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_aircraft_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('document_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_records_id'))
        batch_op.drop_index(batch_op.f('ix_document_records_component_id'))
        batch_op.drop_index(batch_op.f('ix_document_records_aircraft_id'))

    op.drop_table('document_records')
    with op.batch_alter_table('aircraft_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_components_zone'))
        batch_op.drop_index(batch_op.f('ix_aircraft_components_serial_number'))
        batch_op.drop_index(batch_op.f('ix_aircraft_components_id'))
        batch_op.drop_index(batch_op.f('ix_aircraft_components_component_code'))
        batch_op.drop_index(batch_op.f('ix_aircraft_components_aircraft_id'))

    op.drop_table('aircraft_components')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technicians_specialty'))
        batch_op.drop_index(batch_op.f('ix_technicians_id'))
        batch_op.drop_index(batch_op.f('ix_technicians_employee_code'))
        batch_op.drop_index(batch_op.f('ix_technicians_current_status'))

    op.drop_table('technicians')
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_parts_part_number'))
        batch_op.drop_index(batch_op.f('ix_spare_parts_id'))
        batch_op.drop_index(batch_op.f('ix_spare_parts_category'))

    op.drop_table('spare_parts')
    with op.batch_alter_table('model_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_evaluations_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_model_evaluations_evaluation_timestamp'))

    op.drop_table('model_evaluations')
    with op.batch_alter_table('maintenance_bays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_bays_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_bays_current_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_bays_bay_code'))

    op.drop_table('maintenance_bays')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aircraft_tail_number'))
        batch_op.drop_index(batch_op.f('ix_aircraft_status'))
        batch_op.drop_index(batch_op.f('ix_aircraft_squadron'))
        batch_op.drop_index(batch_op.f('ix_aircraft_risk_level'))
        batch_op.drop_index(batch_op.f('ix_aircraft_id'))
        batch_op.drop_index(batch_op.f('ix_aircraft_base_location'))
        batch_op.drop_index(batch_op.f('ix_aircraft_aircraft_type'))

    op.drop_table('aircraft')
    # ### end Alembic commands ###
